"""Unit tests for the AIS (Annual Information Statement) parser.

Tests cover both the JSON and PDF entry points.
Fake data is generated by tests/fixtures/ais_factory.py.
"""
from __future__ import annotations

import pytest

from kara_api.parsers.ais import AISDocument, parse_ais_json, parse_ais_pdf
from tests.fixtures.ais_factory import build_ais_json, build_ais_pdf


# ---------------------------------------------------------------------------
# JSON path tests
# ---------------------------------------------------------------------------


class TestParseAISJsonBasicCategories:
    """parse_ais_json() should populate salary, interest, and security lists."""

    @pytest.fixture(scope="class")
    def doc(self) -> AISDocument:
        return parse_ais_json(build_ais_json())

    def test_returns_ais_document(self, doc: AISDocument):
        assert isinstance(doc, AISDocument)

    def test_pan_extracted(self, doc: AISDocument):
        assert doc.pan == "ABCDE1234F"

    def test_assessment_year_extracted(self, doc: AISDocument):
        assert doc.assessment_year == "2025-26"

    def test_name_extracted(self, doc: AISDocument):
        assert doc.name == "Rajesh Kumar"

    def test_salary_populated(self, doc: AISDocument):
        assert len(doc.salary_reported) == 1
        assert doc.salary_reported[0].deductor_name == "Acme Software Pvt Ltd"

    def test_interest_savings_populated(self, doc: AISDocument):
        # "Savings" account type → interest_savings list
        assert len(doc.interest_savings) == 1
        assert "Bank" in doc.interest_savings[0].payer_name or doc.interest_savings[0].payer_name

    def test_security_sales_populated(self, doc: AISDocument):
        assert len(doc.security_sales) == 1
        sale = doc.security_sales[0]
        assert sale.isin == "INE009A01021"
        assert sale.txn_type == "sell"

    def test_source_is_json(self, doc: AISDocument):
        assert doc.source == "json"


class TestParseAISJsonUnknownCategory:
    """Unknown category codes must emit a warning and not crash."""

    @pytest.fixture(scope="class")
    def doc(self) -> AISDocument:
        return parse_ais_json(build_ais_json())

    def test_warning_emitted_for_sft999(self, doc: AISDocument):
        unknown_warnings = [
            w for w in doc.warnings if w.code == "unknown_category"
        ]
        assert len(unknown_warnings) >= 1

    def test_warning_mentions_sft999(self, doc: AISDocument):
        codes_mentioned = " ".join(
            w.message for w in doc.warnings if w.code == "unknown_category"
        )
        assert "SFT-999" in codes_mentioned

    def test_no_crash_for_unknown_category(self, doc: AISDocument):
        # Parser must still return a valid document
        assert isinstance(doc, AISDocument)


class TestParseAISJsonAmountNormalization:
    """Amounts must be stored as integer paise."""

    @pytest.fixture(scope="class")
    def doc(self) -> AISDocument:
        return parse_ais_json(build_ais_json())

    def test_salary_amount_is_paise(self, doc: AISDocument):
        # Factory sets Amount_Paid = "1200000" rupees → 120000000 paise
        assert doc.salary_reported[0].amount_paid == 120000000

    def test_salary_tds_is_paise(self, doc: AISDocument):
        # TDS_Amount = "60000" → 6000000 paise
        assert doc.salary_reported[0].tds_deducted == 6000000

    def test_interest_amount_is_paise(self, doc: AISDocument):
        # Interest_Amount = "45000" → 4500000 paise
        assert doc.interest_savings[0].amount == 4500000

    def test_security_sale_value_is_paise(self, doc: AISDocument):
        # Sale_Value = "1500000" → 150000000 paise
        assert doc.security_sales[0].value == 150000000

    def test_amounts_are_integers(self, doc: AISDocument):
        assert isinstance(doc.salary_reported[0].amount_paid, int)
        assert isinstance(doc.interest_savings[0].amount, int)


class TestParseAISJsonTotalsPopulated:
    """Totals must be computed correctly from the parsed lists."""

    @pytest.fixture(scope="class")
    def doc(self) -> AISDocument:
        return parse_ais_json(build_ais_json())

    def test_total_salary_is_sum(self, doc: AISDocument):
        expected = sum(e.amount_paid for e in doc.salary_reported)
        assert doc.totals.total_salary_reported == expected

    def test_total_interest_is_sum(self, doc: AISDocument):
        expected = sum(e.amount for e in doc.interest_savings) + sum(
            e.amount for e in doc.interest_fd
        )
        assert doc.totals.total_interest == expected

    def test_total_capital_gains_value_is_sum(self, doc: AISDocument):
        expected = sum(e.value for e in doc.security_sales) + sum(
            e.amount for e in doc.mutual_fund_redemptions
        )
        assert doc.totals.total_capital_gains_value == expected

    def test_totals_are_non_negative(self, doc: AISDocument):
        t = doc.totals
        assert t.total_interest >= 0
        assert t.total_dividends >= 0
        assert t.total_salary_reported >= 0


class TestParseAISHandlesEmptyCategories:
    """Parser must handle JSON with empty or missing Transaction_Data gracefully."""

    def test_empty_transaction_data(self):
        blob = {
            "PAN": "ABCDE1234F",
            "AIS_Data": [
                {
                    "Information_Category": "192",
                    "Transaction_Data": [],  # empty list
                }
            ],
        }
        doc = parse_ais_json(blob)
        assert isinstance(doc, AISDocument)
        assert doc.salary_reported == []

    def test_missing_transaction_data(self):
        blob = {
            "PAN": "ABCDE1234F",
            "AIS_Data": [
                {
                    "Information_Category": "192",
                    # No Transaction_Data key at all
                }
            ],
        }
        doc = parse_ais_json(blob)
        assert isinstance(doc, AISDocument)

    def test_no_ais_data_key(self):
        blob = {"PAN": "ABCDE1234F", "Assessment_Year": "2025-26"}
        doc = parse_ais_json(blob)
        assert any(w.code == "no_ais_data" for w in doc.warnings)

    def test_nested_annual_information_statement_wrapper(self):
        blob = {
            "Annual_Information_Statement": {
                "PAN": "ABCDE1234F",
                "AIS_Data": [
                    {
                        "Information_Category": "194",
                        "Transaction_Data": [
                            {"Payer_Name": "ABC Corp", "Amount": "5000", "TDS_Amount": "500"}
                        ],
                    }
                ],
            }
        }
        doc = parse_ais_json(blob)
        assert len(doc.dividends) == 1
        assert doc.dividends[0].payer_name == "ABC Corp"


# ---------------------------------------------------------------------------
# PDF path tests
# ---------------------------------------------------------------------------


class TestParseAISPDF:
    """parse_ais_pdf() must return an AISDocument without crashing."""

    @pytest.fixture(scope="class")
    def doc(self) -> AISDocument:
        return parse_ais_pdf(build_ais_pdf())

    def test_returns_ais_document(self, doc: AISDocument):
        assert isinstance(doc, AISDocument)

    def test_source_is_pdf(self, doc: AISDocument):
        assert doc.source == "pdf"

    def test_pan_extracted(self, doc: AISDocument):
        # PAN is in the PDF header text
        assert doc.pan == "ABCDE1234F"

    def test_no_crash(self, doc: AISDocument):
        # The parser completed without raising
        assert doc is not None

    def test_totals_computed(self, doc: AISDocument):
        # Totals should be populated (even if all zero for a minimal PDF)
        assert isinstance(doc.totals.total_salary_reported, int)
        assert isinstance(doc.totals.total_interest, int)


def test_parse_ais_pdf_garbage_bytes():
    """Garbage bytes must return an AISDocument with a warning, not raise."""
    doc = parse_ais_pdf(b"not a real pdf")
    assert isinstance(doc, AISDocument)
    # Should have at least one warning
    assert len(doc.warnings) >= 1


def test_parse_ais_pdf_empty_bytes():
    """Empty bytes must return an AISDocument with a warning."""
    doc = parse_ais_pdf(b"")
    assert isinstance(doc, AISDocument)
    assert len(doc.warnings) >= 1
