"""Unit tests for the Form 26AS PDF parser.

Fake PDFs are generated by tests/fixtures/twenty_six_as_factory.py.
"""
from __future__ import annotations

import pytest

from kara_api.parsers.twenty_six_as import Form26ASDocument, parse_form_26as
from tests.fixtures.twenty_six_as_factory import build_26as_pdf

# ---------------------------------------------------------------------------
# PART A — Salary TDS
# ---------------------------------------------------------------------------


class TestParse26ASPartASalary:
    """PART A table must be parsed into tds_on_salary entries."""

    @pytest.fixture(scope="class")
    def doc(self) -> Form26ASDocument:
        return parse_form_26as(
            build_26as_pdf(
                employer_tan="MUMB12345A",
                tds_salary_amount=1200000,
                tds_salary_deducted=185000,
            )
        )

    def test_returns_form26as_document(self, doc: Form26ASDocument):
        assert isinstance(doc, Form26ASDocument)

    def test_tds_on_salary_populated(self, doc: Form26ASDocument):
        assert len(doc.tds_on_salary) >= 1

    def test_employer_tan_present(self, doc: Form26ASDocument):
        tans = [e.deductor_tan for e in doc.tds_on_salary]
        assert "MUMB12345A" in tans

    def test_tax_deducted_in_paise(self, doc: Form26ASDocument):
        # 185,000 rupees → 18,500,000 paise
        total = sum(e.tax_deducted for e in doc.tds_on_salary)
        assert total == 18500000

    def test_amount_paid_in_paise(self, doc: Form26ASDocument):
        # 1,200,000 rupees → 120,000,000 paise
        total = sum(e.amount_paid_credited for e in doc.tds_on_salary)
        assert total == 120000000

    def test_source_is_pdf(self, doc: Form26ASDocument):
        assert doc.source == "pdf"


# ---------------------------------------------------------------------------
# Refund section
# ---------------------------------------------------------------------------


class TestParse26ASPartDRefund:
    """PART D table must be parsed into refunds entries."""

    @pytest.fixture(scope="class")
    def doc(self) -> Form26ASDocument:
        return parse_form_26as(build_26as_pdf())

    def test_refunds_populated(self, doc: Form26ASDocument):
        assert len(doc.refunds) >= 1

    def test_refund_amount_in_paise(self, doc: Form26ASDocument):
        # Factory sets refund amount to 15,000 rupees → 1,500,000 paise
        total = sum(r.refund_amount for r in doc.refunds)
        assert total == 1500000

    def test_refund_interest_in_paise(self, doc: Form26ASDocument):
        # Factory sets interest to 500 rupees → 50,000 paise
        total = sum(r.interest for r in doc.refunds)
        assert total == 50000


# ---------------------------------------------------------------------------
# Missing PART D (no crash test)
# ---------------------------------------------------------------------------


def test_parse_26as_missing_part_d_no_crash():
    """A 26AS PDF without a refund section must not crash."""
    import io

    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet
    from reportlab.platypus import Paragraph, SimpleDocTemplate

    buf = io.BytesIO()
    styles = getSampleStyleSheet()
    doc = SimpleDocTemplate(buf, pagesize=A4)
    story = [
        Paragraph("<b>FORM 26AS</b>", styles["Heading1"]),
        Paragraph("PAN: ABCDE1234F", styles["Normal"]),
        Paragraph("Assessment Year: 2025-26", styles["Normal"]),
        Paragraph("<b>PART A</b>", styles["Heading2"]),
        Paragraph("No data available.", styles["Normal"]),
    ]
    doc.build(story)
    pdf_bytes = buf.getvalue()

    result = parse_form_26as(pdf_bytes)
    assert isinstance(result, Form26ASDocument)
    assert result.refunds == []


# ---------------------------------------------------------------------------
# Currency formatting
# ---------------------------------------------------------------------------


class TestParse26ASCurrencyFormatting:
    """All monetary amounts must be stored as integer paise."""

    @pytest.fixture(scope="class")
    def doc(self) -> Form26ASDocument:
        return parse_form_26as(build_26as_pdf())

    def test_tds_deducted_is_int(self, doc: Form26ASDocument):
        for entry in doc.tds_on_salary:
            assert isinstance(entry.tax_deducted, int)

    def test_tds_deposited_is_int(self, doc: Form26ASDocument):
        for entry in doc.tds_on_salary:
            assert isinstance(entry.tax_deposited, int)

    def test_refund_amount_is_int(self, doc: Form26ASDocument):
        for refund in doc.refunds:
            assert isinstance(refund.refund_amount, int)

    def test_amounts_non_negative(self, doc: Form26ASDocument):
        for entry in doc.tds_on_salary:
            assert entry.tax_deducted >= 0
            assert entry.amount_paid_credited >= 0

    def test_totals_computed(self, doc: Form26ASDocument):
        expected_salary_tds = sum(e.tax_deducted for e in doc.tds_on_salary)
        assert doc.totals.total_tds_salary == expected_salary_tds


# ---------------------------------------------------------------------------
# PAN extraction
# ---------------------------------------------------------------------------


class TestParse26ASPanExtracted:
    """PAN must be extracted from the PDF header text."""

    @pytest.fixture(scope="class")
    def doc(self) -> Form26ASDocument:
        return parse_form_26as(build_26as_pdf(pan="ABCDE1234F"))

    def test_pan_extracted(self, doc: Form26ASDocument):
        assert doc.pan == "ABCDE1234F"

    def test_assessment_year_extracted(self, doc: Form26ASDocument):
        assert doc.assessment_year == "2025-26"


# ---------------------------------------------------------------------------
# Edge cases
# ---------------------------------------------------------------------------


def test_parse_26as_garbage_bytes_no_crash():
    """Garbage bytes must return a Form26ASDocument with warnings, not raise."""
    doc = parse_form_26as(b"not a real pdf at all")
    assert isinstance(doc, Form26ASDocument)
    assert len(doc.warnings) >= 1


def test_parse_26as_empty_bytes_no_crash():
    """Empty bytes must return a Form26ASDocument with warnings, not raise."""
    doc = parse_form_26as(b"")
    assert isinstance(doc, Form26ASDocument)
    assert len(doc.warnings) >= 1


class TestParse26ASEncrypted:
    """TRACES 26AS PDFs are password-protected (DOB as DDMMYYYY); the parser
    must surface that instead of a generic open failure."""

    def test_encrypted_pdf_without_password_raises(self):
        from kara_api.parsers._common import PdfPasswordError

        pdf_bytes = build_26as_pdf(password="01011990")
        with pytest.raises(PdfPasswordError, match="[Pp]assword"):
            parse_form_26as(pdf_bytes)

    def test_encrypted_pdf_with_correct_password_parses(self):
        from kara_api.parsers._common import PdfPasswordError

        pdf_bytes = build_26as_pdf(password="01011990")
        try:
            doc = parse_form_26as(pdf_bytes, password="01011990")
        except PdfPasswordError:
            pytest.skip("environment cannot decrypt this PDF even with the password")
        assert doc.pan == "ABCDE1234F"
