"""The 20 golden regression profiles.

Inputs only — expected outputs live in expected.json, generated by
``python tests/golden/generate.py`` and committed. Regenerate ONLY when a
computation change is intentional and reviewed; any unexplained diff in
expected.json is a regression.
"""

PROFILES: dict[str, dict] = {
    # --- new regime basics -------------------------------------------------
    "new_regime_15L_salaried": {
        "gross_salary": 1_500_000, "regime": "new",
    },
    "new_regime_rebate_zone_10L": {
        "gross_salary": 1_000_000, "regime": "new",
    },
    "new_regime_rebate_boundary_1275000": {
        "gross_salary": 1_275_000, "regime": "new",
    },
    "new_regime_marginal_relief_1325000": {
        "gross_salary": 1_325_000, "regime": "new",
    },
    "new_regime_50L_high_earner": {
        "gross_salary": 5_000_000, "regime": "new",
    },
    "new_regime_surcharge_60L": {
        "gross_salary": 6_000_000, "regime": "new",
    },
    "new_regime_surcharge_cap_6cr": {
        "gross_salary": 60_000_000, "regime": "new",
    },
    # --- old regime --------------------------------------------------------
    "old_regime_12L_full_80c": {
        "gross_salary": 1_200_000, "regime": "old",
        "deductions": {"80C": 150_000, "80D": 25_000},
    },
    "old_regime_rebate_5L_boundary": {
        "gross_salary": 550_000, "regime": "old",
    },
    "old_regime_senior_pension_8L": {
        "gross_salary": 800_000, "regime": "old", "age_category": "senior",
        "deductions": {"80D": 50_000, "80TTB": 50_000},
    },
    "old_regime_super_senior_11L": {
        "gross_salary": 1_100_000, "regime": "old", "age_category": "super_senior",
    },
    "old_regime_senior_surcharge_marginal_relief": {
        "gross_salary": 5_050_100, "regime": "old", "age_category": "senior",
    },
    "old_regime_kitchen_sink_25L": {
        "gross_salary": 2_500_000, "regime": "old",
        "deductions": {
            "80C": 150_000, "80CCD1B": 50_000, "80CCD2": 100_000,
            "80D": 25_000, "80D_parents": 50_000, "parents_senior": True,
            "80E": 200_000, "80TTA": 10_000, "24b": 200_000,
        },
    },
    "old_regime_hra_metro": {
        "gross_salary": 1_800_000, "regime": "old",
        "deductions": {"80C": 150_000},
        "hra_details": {
            "hra_received": 300_000, "basic_salary": 720_000,
            "rent_paid": 360_000, "is_metro": True,
        },
    },
    # --- multi-head income --------------------------------------------------
    "business_plus_salary_new": {
        "gross_salary": 800_000, "regime": "new", "business_income": 600_000,
    },
    "house_property_loss_capped": {
        "gross_salary": 1_600_000, "regime": "old",
        "house_property_income": -350_000,
        "deductions": {"80C": 150_000},
    },
    # --- capital gains -----------------------------------------------------
    "equity_ltcg_above_exemption": {
        "gross_salary": 1_200_000, "regime": "new",
        "capital_gains": [
            {
                "asset_class": "listed_equity", "purchase_price": 500_000,
                "sale_price": 900_000, "holding_months": 24,
            }
        ],
    },
    "equity_stcg_short_hold": {
        "gross_salary": 900_000, "regime": "new",
        "capital_gains": [
            {
                "asset_class": "listed_equity", "purchase_price": 400_000,
                "sale_price": 500_000, "holding_months": 6,
            }
        ],
    },
    "crypto_flat_30": {
        "gross_salary": 700_000, "regime": "new",
        "capital_gains": [
            {
                "asset_class": "vda_crypto", "purchase_price": 200_000,
                "sale_price": 500_000, "holding_months": 18,
            }
        ],
    },
    "debt_mf_slab_rate": {
        "gross_salary": 1_000_000, "regime": "new",
        "capital_gains": [
            {
                "asset_class": "debt_mf", "purchase_price": 300_000,
                "sale_price": 420_000, "holding_months": 40,
            }
        ],
    },
}
